### ISSUE TITLE
FIX: Mealsdetails problems

### ISSUE THREAD

**Issue by kira0826** [Vita-mobile/vita-app#100]
Se  debe quitar el botón de descripción y  colocar la descripción en la zona donde se especifíca todos los ingredientes, de primero antes de la descripción de la meal.

![Image](https://github.com/user-attachments/assets/49ec2ed4-01e3-4cdb-9497-183cb697d071)

**Comment by elkofix** [comment]
## Celular
### Con descripción (Generada)
![Image](https://github.com/user-attachments/assets/444a2e1b-d647-46d1-804f-4f8a31828cce)
### Sin descripción (Creada)
![Image](https://github.com/user-attachments/assets/742a9701-3025-492b-bef3-3ea56bfb0f9b)

## Tabllet
![Image](https://github.com/user-attachments/assets/4b9f41ff-c3db-4053-a44f-9625d906bea4)
![Image](https://github.com/user-attachments/assets/d09e9126-63a6-4cb1-ae5b-2617afb23977)
