### ISSUE TITLE
FIX: Dietspreview problems on creation page.

### ISSUE THREAD

**Issue by kira0826** [Vita-mobile/vita-app#102]
Cuando un usuario se logea y no tiene meals en creations, no hay forma o botón para agregar alguna meal. Sin embargo cuando ya tiene meals en creation sí es posible agregar comidas en creation.

![Image](https://github.com/user-attachments/assets/38ffd191-e60f-4973-886b-87b0c2e1a601)

**Comment by elkofix** [comment]
## Tablet
### Sin comidas
![Image](https://github.com/user-attachments/assets/043dccc3-712e-4b7a-b8bd-8ecf3fc9a9c9)
### Con comidas
![Image](https://github.com/user-attachments/assets/339fb640-8b94-4820-a90d-1849796f3e48)

## Celular
### Sin comidas
![Image](https://github.com/user-attachments/assets/26422b2a-b9c8-4b45-a191-418e03b9222e)
### Con comidas
![Image](https://github.com/user-attachments/assets/05d5a79e-1f3a-43ea-83d1-621cd0f37d08)
